name: Build and Deploy to GitHub

# Trigger the action on push to the main branch
on:
  push:
    branches:
      - main  # Adjust if you're using a different branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Run the build process (bundling the JS file)
      - name: Build the project
        run: npm run build

      # Step 5: Commit the built to dist branch
      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add dist/
          git commit -m "Automated build from GitHub Actions"
          git push origin dist
